import {
  Cajas,
  Catalogo,
  Cifras,
  Configuracion,
  DashboardAdmin,
  Movimientos,
  PuntosVentas,
  Reportes,
  Resultados,
  Roles,
  Sorteos,
  Suertes,
  Tickets,
  Usuarios,
} from './admin/index.admin.js'
import Login from './login/Login.jsx'
import {
  CajasVendedor,
  DashboardVendedor,
  SorteosVendedor,
  TicketsVendedor,
} from './vendedor/index.vendedor.js'

export {
  Cajas,
  CajasVendedor,
  Catalogo,
  Cifras,
  Configuracion,
  DashboardAdmin,
  DashboardVendedor,
  Login,
  Movimientos,
  PuntosVentas,
  Reportes,
  Resultados,
  Roles,
  Sorteos,
  SorteosVendedor,
  Suertes,
  Tickets,
  TicketsVendedor,
  Usuarios,
}
